import {
  borderColor,
  defaultTextColor,
  groundColour,
  navBarBackground,
  navBarMenuColor,
  navBarSeparatorColor,
  navBarTitleColor,
  primaryColor,
  primaryColorRgb,
  secondaryColor,
  secondaryColorRgb,
  secondaryTextColor,
  subTextColor,
  tintTextColor
} from '!/theme.json';

export default {
    edgeDistance: 14,
    primaryColor,
    primaryColorRgb,
    secondaryColor,
    secondaryColorRgb,
    defaultTextColor,
    secondaryTextColor,
    subTextColor,
    tintTextColor,
    borderColor,
    groundColour,
    navBarBackground,
    navBarTitleColor,
    navBarMenuColor,
    navBarSeparatorColor,
    yellow: '#FFCC01',
    red: '#F44236',
    boy: '#00C8FF',
    girl: '#FF5C9D',
    watermelon: '#FF5E7D',
    link: '#407FCF',
    cancel: '#b6c2e1',
    slateGray1: '#C4BFCF',
    slateGray2: '#ECEAF3',
    confirm: '#3E65E8',
    correct: '#1CACF9',
    errorColor: '#FF4C4C',
    teaGreen: '#12E2BB',
    weixin: '#47D850',
};
